name: Google Keep <> Bring Sync

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gkeepapi bringapi

      - name: Set up Google authentication token file
        run: echo "${{ secrets.GOOGLE_TOKEN }}" > token.txt

      - name: Run the sync script
        env:
          GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          KEEP_LIST_ID: ${{ secrets.KEEP_LIST_ID }}
          BRING_EMAIL: ${{ secrets.BRING_EMAIL }}
          BRING_PASSWORD: ${{ secrets.BRING_PASSWORD }}
          SYNC_MODE: 0
          TIMEOUT: 60
          BRING_LIST_NAME: 
        run: python sync.py
