name: Google Keep <> Bring Sync

on:
  schedule:
    # This cron schedule runs the workflow at the start of every hour.
    # You can change this to suit your needs.
    # For example, '0 0 * * *' would run it once a day at midnight UTC.
    - cron: '0 */1 * * *'
  
  # This allows you to manually run the workflow from the GitHub Actions tab.
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt # This step must be here!

      - name: Set up Google authentication token file
        run: echo "${{ secrets.GOOGLE_TOKEN }}" > token.txt

      - name: Run the sync script
        env:
          # ... (your environment variables) ...
        run: python sync.py # This step must be last!
